name: exbix_flutter
description: A new Flutter project for crypto exchange.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: '>=3.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_native_splash: ^2.4.0
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  get_storage: ^2.1.1
  intl: ^0.19.0
  connectivity_plus: ^6.0.3
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.6
  cached_network_image: ^3.3.1
  http: ^1.2.1
  image_picker: ^1.1.2
  image_cropper: ^6.0.0
  url_launcher: ^6.2.6
  webview_flutter: ^4.7.0
  webview_flutter_wkwebview: ^3.12.0
  webview_flutter_android: ^3.16.1
  pin_code_fields: ^8.0.1
  auto_size_text: ^3.0.0
  qr_bar_code: ^1.3.0
  flutter_switch: ^0.3.2
  modal_bottom_sheet: ^3.0.0
  web_socket_channel: ^2.4.0
  intl_phone_number_input: ^0.7.4
  country_picker: ^2.0.25
  timeline_tile: ^2.0.0
  share_plus: ^9.0.0
  device_info_plus: ^10.1.0
  easy_refresh: ^3.4.0
  crisp: ^0.3.1
  flutter_keyboard_visibility: ^6.0.0
  flutter_stripe: ^11.1.0
  flutter_dotenv: ^5.1.0
  package_info_plus: ^8.0.0
  http_auth: ^1.0.4
  file: ^7.0.0
  persona_flutter: ^3.2.1
  flutter_widget_from_html: ^0.15.0
  path_provider: ^2.1.3
  carousel_slider: ^5.0.0
  shimmer: ^3.0.0
  k_chart_plus: ^1.0.2
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.1
  flutter_facebook_auth: ^7.0.1
  decimal: ^3.0.2
  flutter_staggered_grid_view: ^0.7.0
  flutter_countdown_timer: ^4.1.0
  textfield_tags: ^3.0.1
  chat_bubbles: ^1.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  change_app_package_name: ^1.3.0  #flutter pub run change_app_package_name:main com.new.package.name
  flutter_recaptcha_v2_compat: ^latest_version

  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icons/icLogo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21 ic_launcher
  web:
    generate: true
    image_path: "assets/icons/icLogo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/icLogo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/icLogo.png"
    #    flutter pub run flutter_launcher_icons


dependency_overrides:
  intl: ^0.18.0
  js: ^0.6.7

# For information on the generic Dart part of this file, see: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is included with your application.
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - .env
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
  # For details regarding fonts see: https://flutter.dev/custom-fonts/#from-packages


flutter_native_splash:
  # https://pub.dev/packages/flutter_native_splash
  # To Create: dart run flutter_native_splash:create
  # To restore default: dart run flutter_native_splash:remove

  color: "#ffffff"
  # background_image: "assets/dark-background.png"
  # splash image, must be png file and density 4x pixel.
  image: assets/icons/ic_app_icon.png
  # The branding image must be a png file. It is supported for Android, iOS and the Web.
  # branding: assets/images/ic_branding.png


  # Android 12 handles the splash screen differently than previous versions.  Please visit
  # https://developer.android.com/guide/topics/ui/splash-screen
  # Following are Android 12 specific parameter.
  android_12:
    # Please note that the splash screen will be clipped to a circle on the center of the screen.
    # App icon with an icon background: This should be 960×960 pixels, and fit within a circle
    # 640 pixels in diameter.
    # App icon without an icon background: This should be 1152×1152 pixels, and fit within a circle
    # 768 pixels in diameter.
    image: assets/icons/ic_app_icon.png
    # Splash screen background color.
    color: "#ffffff"
    # App icon background color.
    # icon_background_color: "#17202A"
    # The branding property allows you to specify an image used as branding in the splash screen.
    # branding: assets/images/ic_branding.png

  # The image_dark, color_dark, icon_background_color_dark, and branding_dark set values that
  image_dark: assets/icons/ic_app_icon.png
  color_dark: "#0F0F0F"
  #icon_background_color_dark: "#17202A"
